useEvalGoICP: false
makeGoICPTest: false
applyIcp: true
plane_extractor: 3 # 1: RHT, 2: RG, 3: PCL
maxTestIter: 100
noiseVariance: 0
GoICPdownsample: "1000" # demo (data_bunny -> model_bunny) if this value is set to 900 or below



