# Intersection Pattern Matcher
IntersectionPatternParallelThreshold: 0.8
IntersectionPatternCornerThreshold: -0.1 #does not work yet, set to zero for no changes
IntersectionPatternCoarseness: 0.1 # Defines radius in which points are bunched together 
IntersectionPatternTriangleDevOffset: 3 # parameter of error/score function
IntersectionPatternTriangleDevGrade: 1 # parameter of error/score function
IntersectionPatternLineDevOffset: 3 # parameter of error/score function
IntersectionPatternLineDevGrade: 0.5 # parameter of error/score function
IntersectionPatternMaxSize: 100



