# Settings of RHT

AccumulatorChoice: 2 # accumulator choice (1: array, 2: ball)
AccumulatorRhoResolution: 0.1 # resolution of rho in discretization of accumulator
AccumulatorThetaResolution: 0.1 # resolution of theta in discretization of accumulator
AccumulatorPsiResolution: 0.1 # resolution of psi in discretization of accumulator
AccumulatorThreshold: 30 # Threshold for votes such that plane gets detected
AccumulatorKMaxSuppress: 5 # neighborhood (max norm) of Non-maxima Suppression, set to zero to deactivate

RHTMaxIter: 1000000 # sample iterations
RHTTolDist: 3    # makes sure points are not too far apart
RHTMinArea: 0.5 # min area spanned by two vectors created by three reference points (makes sure points are not the same or collinear)
RHTPlaneNumber: 0 # number of principal planes, set to zero if all planes should be shown


#Settings of iterative RHT

iterAccumulatorChoice: 2 # accumulator choice (1: array, 2: ball)
iterAccumulatorRhoResolution: 0.05 # resolution of rho in discretization of accumulator
iterAccumulatorThetaResolution: 0.02 # resolution of theta in discretization of accumulator
iterAccumulatorPsiResolution: 0.02 # resolution of psi in discretization of accumulator
iterAccumulatorKMaxSuppress: 0 # neighborhood (max norm) of Non-maxima Suppression, set to zero to deactivate
iterAccumulatorMinThreshold: 30 # Threshold for votes such that plane gets detected

iterRHTIter: 8 # number of rht iterations
iterRHTIterPerIter: 1000000 # sample iterations per iteration
iterRHTTolDist: 3   # makes sure points are not too far apart
iterRHTMinArea: 0.5 # min area spanned by two vectors created by three reference points (makes sure points are not the same or collinear)
iterRHTNumPlanePerIter: 1 # set to zero to use threshold per iteration


# Settings of PCL

PCLDistanceThreshold: 0.1 # max distance between points to plane
PCLMaxNumPlane: 8 # max number of extracted planes
PCLMinInlier: 15 # min number of inliers of detected planes


# Settings of CGAL Region Growing

CGALRegionGrowMinNumInliers: 80 # min number of inliers of detected planes
CGALRegionGrowMaxDistToPlane: 0.07 # max distance between points to plane
CGALRegionGrowMaxDistBetwPoint: 10 # max distance between points to points along plane
CGALRegionGrowMaxDiffNormalThreshold: 0.9 # max difference between normals of points of the same plane

CGALRGRegulActive: true # activate regularization
CGALRGRegulParall: true # activate regularization of parallel planes
CGALRGRegulOrthog: true # activate regularization of orthogonal planes
CGALRGRegulCoplanar: false # activate regularization of coplanar planes
CGALRGRegulParallOrthTol: 10 # threshold for orthogonality and parallelity of planes 
CGALRGRegulCoplanarTol: 0.2 # threshold for coplanarity



