# Intersection Pattern Matcher
IntersectionPatternParallelThreshold: 0.1
IntersectionPatternCornerThreshold: 0.0
IntersectionPatternCoarseness: 1 # Defines radius in which points are bunched together 
IntersectionPatternDevOffset: 1 # parameter of error/score function
IntersectionPatternDevGrade: 1 # parameter of error/score function


