# Settings of accumulator
AccumulatorRhoDivider: 100
AccumulatorThetaDivider: 20
AccumulatorPsiDivider: 10
#AccumulatorFile: path to file which includes a designed accumulator bin pc

# Settings of RHT
RHTMaxIter: 10000
RHTTolDist: 2    # makes sure points are not too far apart
RHTMinArea: 0.05 #*2 makes sure points are not colinear


