# Settings of accumulator
AccumulatorRhoResolution: 0.2
AccumulatorThetaResolution: 0.2
AccumulatorPsiResolution: 0.2
AccumulatorThreshold: 1
#AccumulatorFile: path to file which includes a designed accumulator bin pc

# Settings of RHT
RHTMaxIter: 10000
RHTTolDist: 0.1    # makes sure points are not too far apart
RHTMinArea: 0.05
RHTPlaneNumber: 8 # number of principal planes, set to zero if all planes should be shown


