# Settings of accumulator
AccumulatorRhoResolution: 0.1
AccumulatorThetaResolution: 0.1
AccumulatorPsiResolution: 0.1
AccumulatorThreshold: 10
#AccumulatorFile: path to file which includes a designed accumulator bin pc

# Settings of RHT
RHTMaxIter: 100000
RHTTolDist: 4    # makes sure points are not too far apart
RHTMinArea: 0.5


