groundtruthx: -2
groundtruthy: 2
groundtruthz: 0
groundtruth_orientation: [0.6894984, 0, 0, 0.724872] #w x y z

#LiDAR settings
accuracy_of_lidar: 0.0
range_of_lidar: 50
bin_elevation: [-15, -13, -11, -9, -7, -5, -3, -1, 15, 13, 11, 9, 7, 5, 3, 1]
lidar_angular_resolution: 2
lidar_offset: 1.5 

#ROS settings
tfMapFrame: /map
