#LiDAR settings
accuracy_of_lidar: 0.0
range_of_lidar: 10
bin_elevation: [-15, -13, -11, -9, -7, -5, -3, -1, 15, 13, 11, 9, 7, 5, 3, 1]
lidar_angular_resolution: 2
lidar_offset: 1.5 

#ROS settings
tfMapFrame: /map
