inputQueueSize: 1
tfMapFrame: /map

mapSamplingDensity: 20

usetoyproblem: true

#Select Matcher
Matcher: PlaneMatcher # template, GoICP, PlaneMatcher

# Settings for Plane Matcher

# Filters
useStructureFilter: true
StructureThreshold: 150

useVoxelCentroidFilter: true
Voxelsearchradius: 0.1

# Plane Extraction
PlaneExtractor: iterRhtPlaneExtraction # pclPlaneExtraction, rhtPlaneExtraction, iterRhtPlaneExtraction

# Plane Matching

# Transform Calculation

