inputQueueSize: 1
tfMapFrame: /map

mapSamplingDensity: 20

usetoyproblem: true

#Select Matcher
Matcher: PlaneMatcher # template, GoICP, PlaneMatcher

#Settings for GoICP

#Change MSE Threshold & Trimmer Settings in Go-ICP/demo/config.txt
GoICPdownsample: "1000"

# Settings for Plane Matcher

# Filters
useStructureFilter: false
StructureThreshold: 150

useVoxelCentroidFilter: false
Voxelsearchradius: 0.1

# Plane Extraction
PlaneExtractor: pclPlaneExtraction # pclPlaneExtraction, rhtPlaneExtraction, iterRhtPlaneExtraction
