# Sample density for map
mapSamplingDensity: 20

usetoyproblem: false

#Select Matcher
Matcher: PlaneMatcher # GoICP, PlaneMatcher

#Settings for GoICP

#Change MSE Threshold & Trimmer Settings in Go-ICP/demo/config.txt
GoICPdownsample: "1000"

# Settings for Plane Matcher

# Filters
useStructureFilter: true
StructureThreshold: 150

useVoxelCentroidFilter: true
Voxelsearchradius: 0.2

# Plane Extraction
PlaneExtractor: iterRhtPlaneExtraction # pclPlaneExtraction, rhtPlaneExtraction, 
                                   # iterRhtPlaneExtraction, cgalRegionGrowing

# Plane Matching
PlaneMatch: fail # useMatchSolution, IntersectionPatternMatcher
                  # PRRUS, LineSegmentRansac

# Refinement
applyICP: false


