inputQueueSize: 1
tfMapFrame: /map

mapSamplingDensity: 20

MapPlaneExtractionMinArea: 4 #Min area of a map plane (resp. of facet)
MapPlaneTransThreshold: 0.16 #Max difference between translation along plane normal
MapPlaneTransAlongPlane: 28 #Max distance between points of same plane which will be combined
MapPlaneRotDiffThreshold: 0.9 #Max difference in rotation of normals
MapPlanePos: [23, -1, 1] #Consider planes from this point to get most conventions of normals right

usetoyproblem: false

#Select Matcher
Matcher: PlaneMatcher # template, GoICP, PlaneMatcher

#Settings for GoICP

#Change MSE Threshold & Trimmer Settings in Go-ICP/demo/config.txt
GoICPdownsample: "1000"

# Settings for Plane Matcher

# Filters
useStructureFilter: false
StructureThreshold: 150

useVoxelCentroidFilter: false
Voxelsearchradius: 0.1

# Plane Extraction
PlaneExtractor: cgalRegionGrowing # pclPlaneExtraction, rhtPlaneExtraction, iterRhtPlaneExtraction, cgalRegionGrowing

# Plane Matching (only one)
PlaneMatch: fail # useMatchSolution, IntersectionPatternMatcher, LineSegmentRansac


