inputQueueSize: 1
tfMapFrame: /map

mapSamplingDensity: 20

usetoyproblem: false

#Select Matcher (only one)
usetemplate: true

useGoICP: false

useSuper4PCS: false

usePlaneMatcher: false
# Settings for Plane Matcher
# Filter (several)
useStructureFilter: true
StructureThreshold: 150

useVoxelCentroidFilter: true
Voxelsearchradius: 0.1

# Plane Extraction (only one)
usepclPlaneExtraction: false

useRHTPlaneExtraction: false

useiterRHTPlaneExtraction: true
# Plane Matching (only one)
# Transform Calculation (only one)

