# Sample density for map
mapSamplingDensity: 20

usetoyproblem: true

#Select Matcher
Matcher: PlaneMatcher # template, GoICP, PlaneMatcher

#Settings for GoICP

#Change MSE Threshold & Trimmer Settings in Go-ICP/demo/config.txt
GoICPdownsample: "1000"

# Settings for Plane Matcher

# Filters
useStructureFilter: true
StructureThreshold: 150

useVoxelCentroidFilter: true
Voxelsearchradius: 0.1

# Plane Extraction
PlaneExtractor: cgalRegionGrowing # pclPlaneExtraction, rhtPlaneExtraction, 
                                   # iterRhtPlaneExtraction, cgalRegionGrowing

# Plane Matching
PlaneMatch: IntersectionPatternMatcher # useMatchSolution, IntersectionPatternMatcher, LineSegmentRansac


