inputQueueSize: 1
tfMapFrame: /map

mapSamplingDensity: 20

usetoyproblem: true

#Select Matcher
Matcher: 2 # 0: template, 1: GoICP, 2: PlaneMatcher

# Settings for Plane Matcher

# Filters
useStructureFilter: true
StructureThreshold: 150

useVoxelCentroidFilter: true
Voxelsearchradius: 0.1

# Plane Extraction
PlaneExtractor: 2 # 0: pclPlaneExtraction, 1: rhtPlaneExtraction, 2: iterRhtPlaneExtraction

# Plane Matching

# Transform Calculation

