inputQueueSize: 1

# Deviation Analysis:
planarSegmentation: CGAL # CGAL or PCL
planarSegmentationMethod: REGION_GROWING # RANCAC or REGION_GROWING, only for CGAL
segmentationDistanceThreshold: 0.03 # at least around the precision of the LiDAR, distance to model
segmentationNormalThreshold: 0.9
segmentationClusterDistance: 0.5 # max distance between points in same cluster for CGAL, depends on Lidar beam angle
minNumberOfPlanePoints: 100 # minimum number of plane points necessary for segmentation of a plane
segmentationProbability: 0.05 # only for CGAL Efficient_Ransac