inputQueueSize: 1

# Deviation Analysis:

# Segmentation
planarSegmentation: CGAL # CGAL or PCL
planarSegmentationMethod: REGION_GROWING # RANCAC or REGION_GROWING, only for CGAL
segmentationDistanceThreshold: 0.03 # at least around the precision of the LiDAR, distance to model
segmentationNormalThreshold: 0.1
segmentationClusterDistance: 0.5 # max distance between points in same cluster for CGAL, depends on Lidar beam angle
minNumberOfPlanePoints: 100 # minimum number of plane points necessary for segmentation of a plane
segmentationProbability: 0.05 # only for CGAL Efficient_Ransac

# Association
minPolyhedronArea: 0.05
matchScoreUpperLimit: 2 # above this limit, don't do any association since we don't expect wrong walls to be so wrong
assocAreaRatioUpperLimit: 100 # ratio = (rec. area)/(ref. copl. area), don't do any assoc. if we reach these limits
assocAreaRatioLowerLimit: 0.2
assocLowerLimitThreshold: 0.5 # lower ratio only taken into account if a threshold in m² is not fulfilled