- RandomSamplingDataPointsFilter:
    prob: 0.5
- SurfaceNormalDataPointsFilter:
    knn: 30
    epsilon: 0.3
    keepNormals: 1
    keepDensities: 1
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter
- MaxDensityDataPointsFilter:
    maxDensity: 10000.0
