# Setup
# 0 -> SuperMegaBot, 1 -> Totalstation
SensorType : 1

#For Totalstation only:
TransformationMatrix: [1.0, 0.0, 0.0, 0.0,
                       0.0, 1.0, 0.0, 0.0,
                       0.0, 0.0, 1.0, 0.0,
                       0.0, 0.0, 0.0, 1.0]
StationaryPosition: [5.5, -1.9, 0.5]

ScanPointsFile: "/home/philipp/Schreibtisch/leica/new_scan1_aligned.ply"

########################################################################
### Paths
BuildingModelMeshFile: "/home/philipp/Schreibtisch/data/CLA_MissingParts_4.ply"
UpsampledBuildingModelFile: "/home/philipp/Schreibtisch/data/CLA_MissingParts_4_8m.ply"

ClassificationConfigFile1: "/home/philipp/reconstruction_ws/src/cad-percept/modules/construction/cpt_reconstruction/resources/mesh_ethz_random_forest_random_area1.bin"
ClassificationConfigFile2: "/home/philipp/reconstruction_ws/src/cad-percept/modules/construction/cpt_reconstruction/resources/mesh_ethz_random_forest_random_area2.bin"
ClassificationConfigFile3: "/home/philipp/reconstruction_ws/src/cad-percept/modules/construction/cpt_reconstruction/resources/mesh_ethz_random_forest_random_area3.bin"
ClassificationConfigFile4: "/home/philipp/reconstruction_ws/src/cad-percept/modules/construction/cpt_reconstruction/resources/mesh_ethz_random_forest_random_area4.bin"
ClassificationConfigFile5: "/home/philipp/reconstruction_ws/src/cad-percept/modules/construction/cpt_reconstruction/resources/mesh_ethz_random_forest_random_area5.bin"


OutputAllPointsFile: "/home/philipp/Schreibtisch/ros_dir/outliers_ros.xyz"
OutputOutlierPointsFile: "/home/philipp/Schreibtisch/ros_dir/outliers_ros_full.xyz"
OutputShapesPath: "/home/philipp/Schreibtisch/Shapes/"
OutputMeshesPath: "/home/philipp/Schreibtisch/Meshes/"
OutoutClassificationResultFile: "/home/philipp/Schreibtisch/ros_dir/mesh_classification_test.ply"
OutputMeshingTempPath: "/home/philipp/Schreibtisch/ros_dir/"


########################################################################
### Shape Detection
ModelTolerance: 0.08
OutlierCount: 50000 #Only for SMB

UseBuffer: false
ClearBufferAfterIteration: 2

UseFilter: true
OctreeFilterResolution: 0.02

RANSACProbability: 0.0000001
RANSACMinPoints: 200
RANSACEpsilon: 0.03
RANSACClusterEpsilon: 0.2
RANSACNormalThreshold: 0.80
########################################################################


### Clustering
VoxelGridFilterResolution: 0.01
MinSizeValidPlane: 50
ValidSizeThresholdPlane: 1000
ThresholdSecondEigenvalue: 0.00015
IntervalFusingClusters: 1000
IntervalCleaningClusters: 1000 #200
IntervalForwardingClusters: 10 #200

#Fusing Planes
DotProductNormals: 0.99
DotProductAxis: 0.99
DistanceMatchingPoint: 0.05
Coverage: 0.01

#Conflicting Clusters
DistanceConflictingPoint: 0.03
Overlap: 0.4

DetectionCount: 1

########################################################################
### Classification
CellSize: 0.1
SmoothingIterations: 4
MaxFacetLength: 0.5
NumberOfScales: 5
NRingQuery: 2


########################################################################
### Mesh Generation
UpsampledModelOctreeResolution: 0.05
MinArea: 0.0
DefaultOffset: 0.2

DuplicateDotProduct: 0.999
DuplicateDiffD: 0.02


########################################################################
### Model Integration


