minReadingPointCount: 1000
inputQueueSize: 1
mapSamplingDensity: 100
tfMapFrame: /map
lidarFrame: lidar
minOverlap: 0.5
mappingTrigger: true # this will currently overload the system
updateICPRefTrigger: false # this will currently overload the system