# At the moment these parameters are used for both map and current scan analysis

inputQueueSize: 1

# Deviation Analysis:
buffer_size: 1 # how many scans to merge before analysis
visualize: current # choose which to visualize: "map" or "current"

# Segmentation
planarSegmentation: CGAL # CGAL or PCL
planarSegmentationMethod: REGION_GROWING # RANSAC or REGION_GROWING, only for CGAL
segmentationDistanceThreshold: 0.03 # distance to model, at least around the precision of the LiDAR
segmentationNormalThreshold: 0.1 # normal tolerance in rad
segmentationClusterDistance: 0.5 # max distance between points in same cluster for CGAL, depends on Lidar beam angle
minNumberOfPlanePoints: 100 # minimum number of plane points necessary for segmentation of a plane
segmentationProbability: 0.05 # only for CGAL Efficient_Ransac

# Association
minPolyhedronArea: 0.5 # minimum area of facet
matchScoreUpperLimit: 1.0 # above this limit, don't do any association since we don't expect wrong walls to be so wrong
matchDistPlaneThresh: 1.0 # max. average distance to plane limit between segmented plane and facet
matchMinDistThresh: 0.6 # max. min_distance limit between segmented plane and facet
matchDistThresh: 1.0 # max. average distance between segmented plane and facet
matchAngleThresh: 0.5 # max angle between pc and facet [rad]
assocAreaRatioUpperLimit: 100.0 # ratio = (rec. area)/(ref. copl. area), don't do any assoc. if we reach these limits
assocAreaRatioLowerLimit: 0.2
assocAreaLowerLimitThreshold: 0.1 # lower ratio only taken into account if a threshold in m² is not fulfilled
minDistWeight: 0.0 # weight for the association score
distPlaneWeight: 1.0 # weight for the association score
angleWeight: 0.0 # weight for the association score
distWeight: 0.0 # weight for the association score
