# Settings of accumulator
AccumulatorChoice: 2 # 1: array, 2: ball
#AccumulatorSlopeThreshold: 2
AccumulatorRhoResolution: 0.5
AccumulatorThetaResolution: 0.3
AccumulatorPsiResolution: 0.3
AccumulatorThreshold: 10
AccumulatorKMaxSuppress: 14 # set to zero to deactivate
#AccumulatorFile: path to file which includes a designed accumulator bin pc

# Settings of RHT
RHTMaxIter: 100000
RHTTolDist: 2    # makes sure points are not too far apart
RHTMinArea: 0.5
RHTPlaneNumber: 0 # number of principal planes, set to zero if all planes should be shown



